CREATE TABLE IF NOT EXISTS GrabTimeLog(
    GrabDate UNSIGNED BIGINT NOT NULL,
    GrabTime UNSIGNED BIGINT NOT NULL,
    
    CONSTRAINT pk_GrabTimeLog PRIMARY KEY (GrabDate,GrabTime)
);

CREATE TABLE IF NOT EXISTS Playlists (
    Pid UNSIGNED BIGINT PRIMARY KEY,
    Name TEXT NOT NULL,
    Subscribed BOOLEAN NOT NULL,
    TrackCount UNSIGNED BIGINT NOT NULL,
    Avartar TEXT
);

CREATE TABLE IF NOT EXISTS Songs (
    Sid UNSIGNED BIGINT PRIMARY KEY,
    Name TEXT NOT NULL,
    Available UNSIGNED BIGINT NOT NULL
);

CREATE TABLE IF NOT EXISTS Belongs (
    Sid UNSIGNED BIGINT NOT NULL,
    Pid UNSIGNED BIGINT NOT NULL,
    
    CONSTRAINT pk_SPid PRIMARY KEY (Sid,Pid),
    CONSTRAINT fk_Sid 
        FOREIGN KEY (Sid) REFERENCES Songs (Sid),
    CONSTRAINT fk_Pid
        FOREIGN KEY (Pid) REFERENCES PlayLists (Pid)
);

CREATE TABLE IF NOT EXISTS Playlists_Changes (
    ChangeDate UNSIGNED BIGINT NOT NULL,
    ChangeType TEXT NOT NULL DEFAULT "CHG",
    Pid UNSIGNED BIGINT NOT NULL,
    OldName TEXT,
    NewName TEXT,
    SongsAdded UNSIGNED BIGINT NOT NULL DEFAULT 0,
    SongsDeleted UNSIGNED BIGINT NOT NULL DEFAULT 0,
    
    CONSTRAINT pk_PC 
        PRIMARY KEY (ChangeDate,Pid)
);

CREATE TABLE IF NOT EXISTS Songs_Changes (
    ChangeDate UNSIGNED BIGINT NOT NULL,
    ChangeType TEXT NOT NULL,
    Sid UNSIGNED BIGINT NOT NULL,
    OldAvailable TINYINT DEFAULT 255,
    NewAvailable TINYINT DEFAULT 255,
    OldName TEXT,
    NewName TEXT,
    
    CONSTRAINT pk_SC 
        PRIMARY KEY (ChangeDate,Sid)
);

CREATE TABLE IF NOT EXISTS Belongs_Changes (
    ChangeDate UNSIGNED BIGINT NOT NULL,
    ChangeType TEXT NOT NULL,
    Sid UNSIGNED BIGINT NOT NULL,
    Pid UNSIGNED BIGINT NOT NULL,
    
    CONSTRAINT pk_BC
        PRIMARY KEY (ChangeDate,Sid,Pid)
);

CREATE TABLE IF NOT EXISTS __Playlists (
    Pid UNSIGNED BIGINT PRIMARY KEY,
    Name TEXT NOT NULL,
    Subscribed BOOLEAN NOT NULL,
    TrackCount UNSIGNED BIGINT NOT NULL,
    Avartar TEXT
);

CREATE TABLE IF NOT EXISTS __Songs (
    Sid UNSIGNED BIGINT PRIMARY KEY,
    Name TEXT NOT NULL,
    Available UNSIGNED BIGINT NOT NULL
);

CREATE TABLE IF NOT EXISTS __Belongs (
    Sid UNSIGNED BIGINT NOT NULL,
    Pid UNSIGNED BIGINT NOT NULL,
    
    CONSTRAINT pk_SPid PRIMARY KEY (Sid,Pid),
    CONSTRAINT fk_Sid 
        FOREIGN KEY (Sid) REFERENCES Songs (Sid),
    CONSTRAINT fk_Pid
        FOREIGN KEY (Pid) REFERENCES PlayLists (Pid)
);

CREATE TABLE IF NOT EXISTS All_Songs (
    Sid UNSIGNED BIGINT PRIMARY KEY,
    Name TEXT NOT NULL,
    Available UNSIGNED BIGINT NOT NULL
);

CREATE TABLE IF NOT EXISTS All_Playlists (
    Pid UNSIGNED BIGINT PRIMARY KEY,
    Name TEXT NOT NULL,
    Subscribed BOOLEAN NOT NULL,
    TrackCount UNSIGNED BIGINT NOT NULL,
    Avartar TEXT
);